//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarshareService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public int UserID { get; set; }
        public int GroupID { get; set; }
        public bool IsAdmin { get; set; }
        public byte Position { get; set; }
        public int ID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
